rem run in "M:\bw1bect0_OBCU_ATP_CONSTRUCTION_int\TGMT_OBCU_ATP\ATP_BUILD\GEN\Appl" to produce "APPL.omf"
M:\bw1bect0_OBCU_ATP_CONSTRUCTION_int\TGMT_DevTools\cadul\bin\link386 -CPLUS NEAR -NODUPLICATE SOURCEQUELLID_* -XREF -SYMBOLMAP all -DEBUG -LONGMAP -MESSAGEOFF 202 -BUILDFILE M:\bw1bect0_OBCU_ATP_CONSTRUCTION_int\TGMT_OBCU_ATP\TOOLS\gen_makefile\target.bld -PRINT APPL.ma2 -OBJECT APPL.omf APPL.prg M:\bw1bect0_OBCU_ATP_CONSTRUCTION_int\TGMT_DevTools\cadul\lib\i386clong.lib M:\bw1bect0_OBCU_ATP_CONSTRUCTION_int\TGMT_Import\OS_TCC\lib\sllstubs.lib

